services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_DB: book_social_network
      POSTGRES_USER: vnq
      POSTGRES_PASSWORD: vuong2003
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - book-social-network
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - book-social-network
    restart: unless-stopped

networks:
    book-social-network:
        driver: bridge

volumes:
  postgres:
    driver: local