/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { BookRequest } from './models/book-request';
export type { BookResponse } from './models/book-response';
export type { BorrowedBookResponse } from './models/borrowed-book-response';
export type { FeedbackRequest } from './models/feedback-request';
export type { FeedbackResponse } from './models/feedback-response';
export type { PageResponeBookResponse } from './models/page-respone-book-response';
export type { PageResponeBorrowedBookResponse } from './models/page-respone-borrowed-book-response';
export type { PageResponeFeedbackResponse } from './models/page-respone-feedback-response';
export type { RegistrationRequest } from './models/registration-request';
