/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getAllFeedbacksByBook } from '../fn/feedback/get-all-feedbacks-by-book';
import { GetAllFeedbacksByBook$Params } from '../fn/feedback/get-all-feedbacks-by-book';
import { PageResponeFeedbackResponse } from '../models/page-respone-feedback-response';
import { saveFeedback } from '../fn/feedback/save-feedback';
import { SaveFeedback$Params } from '../fn/feedback/save-feedback';


/**
 * Feedback API
 */
@Injectable({ providedIn: 'root' })
export class FeedbackService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `saveFeedback()` */
  static readonly SaveFeedbackPath = '/feedbacks';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveFeedback()` instead.
   *
   * This method doesn't expect any request body.
   */
  saveFeedback$Response(params: SaveFeedback$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveFeedback(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveFeedback$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  saveFeedback(params: SaveFeedback$Params, context?: HttpContext): Observable<number> {
    return this.saveFeedback$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getAllFeedbacksByBook()` */
  static readonly GetAllFeedbacksByBookPath = '/feedbacks/book/{book-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllFeedbacksByBook()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllFeedbacksByBook$Response(params: GetAllFeedbacksByBook$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponeFeedbackResponse>> {
    return getAllFeedbacksByBook(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllFeedbacksByBook$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllFeedbacksByBook(params: GetAllFeedbacksByBook$Params, context?: HttpContext): Observable<PageResponeFeedbackResponse> {
    return this.getAllFeedbacksByBook$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponeFeedbackResponse>): PageResponeFeedbackResponse => r.body)
    );
  }

}
