spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: vnq
    password: vuong2003
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: admin
    password: admin
    properties:
      mail.:
        smtp:
          trust: "*"
        auth: false
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

appication:
  security:
    jwt:
      secret-key: RxspgTbD8AzItMQz6o3cAyt+AucpYD/ezWSrFif8CqIFMvUASRVRFfiNWSmsRcNy
      expiration-time: 86400000
    mailing:
      front-end:
        activation-url: http://localhost:4200/activate-account
    file:
      upload:
        photo-output-path: ./uploads